version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: monthly
    time: '12:00'
  pull-request-branch-name:
    separator: '-'
  open-pull-requests-limit: 1
  cooldown:
    default-days: 14
  groups:
    all-dependencies:
      patterns:
        - "*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
    time: '12:00'
  pull-request-branch-name:
    separator: '-'
  open-pull-requests-limit: 1
  cooldown:
    default-days: 14
  groups:
    all-actions:
      patterns:
        - "*"
