name: API spec

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "*"

jobs:
  api-spec:
    name: API spec tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]

    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch

      - name: Setup environment and run API spec tests
        env:
          SECRET_KEY: secret_key
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
        run: |
          hatch run +py=${{ matrix.python-version }} unit_tests:test --version
          hatch env create +py=${{ matrix.python-version }} unit_tests
          ENV_PATH=$(hatch env find +py=${{ matrix.python-version }} unit_tests)
          $ENV_PATH/bin/alembic upgrade head
          $ENV_PATH/bin/uvicorn app.main:app &
          sleep 5
          APIURL=http://localhost:8000/api ./postman/run-api-tests.sh
          $ENV_PATH/bin/alembic downgrade base
